# Generated by Django 5.1.3 on 2025-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='12345678901'),
            preserve_default=False,
        ),
    ]
