# Generated by Django 5.1.3 on 2024-12-08 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_avatar_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
